#%RAML 1.0 NamedExample
-
  airline: Indigo
  flightCode: IND201
  fromAirportCode: HYD
  toAirportCode: BLR
  departureDate: 24-12-2020
  emptySeats: 30
  totalSeats: 150
  price: 750
  planeType: IND 755
 